// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCpVJjlXb8gB6Db9E84qMHFHKSwmmpCY',
    appId: '1:217888141653:web:d7e3ef8b21e6f27d49ffdc',
    messagingSenderId: '217888141653',
    projectId: 'solar-insight-pro',
    authDomain: 'solar-insight-pro.firebaseapp.com',
    storageBucket: 'solar-insight-pro.firebasestorage.app',
    measurementId: 'G-GTMDR96ZVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQibSPzeDth3RahxWmSZsOsKfCVsDgfTE',
    appId: '1:217888141653:android:b4d602a0a7ccbe8e49ffdc',
    messagingSenderId: '217888141653',
    projectId: 'solar-insight-pro',
    storageBucket: 'solar-insight-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxotHlnpcB-Gln2Prh6F9d3NRWMQgM-bA',
    appId: '1:217888141653:ios:cde802e577c515d149ffdc',
    messagingSenderId: '217888141653',
    projectId: 'solar-insight-pro',
    storageBucket: 'solar-insight-pro.firebasestorage.app',
    iosBundleId: 'com.example.solarInsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxotHlnpcB-Gln2Prh6F9d3NRWMQgM-bA',
    appId: '1:217888141653:ios:cde802e577c515d149ffdc',
    messagingSenderId: '217888141653',
    projectId: 'solar-insight-pro',
    storageBucket: 'solar-insight-pro.firebasestorage.app',
    iosBundleId: 'com.example.solarInsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnCpVJjlXb8gB6Db9E84qMHFHKSwmmpCY',
    appId: '1:217888141653:web:03ee693b3961e06649ffdc',
    messagingSenderId: '217888141653',
    projectId: 'solar-insight-pro',
    authDomain: 'solar-insight-pro.firebaseapp.com',
    storageBucket: 'solar-insight-pro.firebasestorage.app',
    measurementId: 'G-VHENCXCRNR',
  );
}
